[package]
name = "kong_rs_macros"
version = "0.2.0"
edition = "2024"
description = "Convenience macros for kong_rs"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"

[lib]
proc-macro = true
